using System.ComponentModel;

namespace CoreUtilities
{
    public enum SqlServerType
    {
        [Description("sysname")]
        SysName,
        [Description("bigint")]
        Bigint,
        [Description("binary")]
        Binary,
        [Description("bit")]
        Bit,
        [Description("char")]
        Char,
        [Description("date")]
        Date,
        [Description("datetime")]
        DateTime,
        [Description("datetime2")]
        DateTime2,
        [Description("datetimeoffset")]
        DateTimeOffset,
        [Description("decimal")]
        Decimal,
        [Description("filestream")]
        FileStream,
        [Description("float")]
        Float,
        [Description("geography")]
        Geography,
        [Description("geometry")]
        Geometry,
        [Description("hierarchyid")]
        HierarchyId,
        [Description("image")]
        Image,
        [Description("int")]
        Int,
        [Description("money")]
        Money,
        [Description("nchar")]
        NChar,
        [Description("ntext")]
        NText,
        [Description("numeric")]
        Numeric,
        [Description("nvarchar")]
        NVarChar,
        [Description("real")]
        Real,
        [Description("rowversion")]
        RowVersion,
        [Description("smalldatetime")]
        SmallDateTime,
        [Description("smallint")]
        SmallInt,
        [Description("smallmoney")]
        SmallMoney,
        [Description("sql_variant")]
        SqlVariant,
        [Description("text")]
        Text,
        [Description("time")]
        Time,
        [Description("timestamp")]
        TimeStamp,
        [Description("tinyint")]
        TinyInt,
        [Description("uniqueidentifier")]
        UniqueIdentifier,
        [Description("varbinary")]
        VarBinary,
        [Description("varchar")]
        Varhar,
        [Description("xml")]
        Xml
    }
}
